version: '3.4'

services:
  api:
    image: api
    build:
      context: api
      target: ${APP_ENV}
      args:
        APP_HOME: ${APP_HOME}
    ports:
      - ${API_PORT_FORWARD}:${API_PORT}
      - ${API_DEBUG_PORT_FORWARD}:${API_DEBUG_PORT}
      - ${PRISMA_PORT_FORWARD}:${PRISMA_PORT}
    volumes:
      - .:${APP_HOME}
    links:
      - db
    restart: on-failure
    command: npm run dev:debug

  db:
    image: postgres:14-alpine
    container_name: budget_db
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - budget_pgdata:/var/lib/postgresql/data
    ports: 
      - ${DB_PORT_FORWARD}:${DB_PORT}
    restart: always

volumes:
  budget_pgdata:
    external: true