services:
  db:
    container_name: flow_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    hostname: postgres
    image: postgres:14-alpine
    ports: 
      - ${DB_PORT_FORWARD}:${DB_PORT}
    restart: always
    volumes:
      - flow_pgdata:/var/lib/postgresql/data
        
volumes:
  flow_pgdata:
    external: true
