#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


x=1

if git diff --cached --name-only --quiet -- "client/*.ts"; then
  echo "%=============================================================================================%"
  echo "= $x No .ts changes in Client (Skipping)"
  echo "%=============================================================================================%"
else
  echo "%=============================================================================================%"
  echo "= $x:C Removing environment variables..."
  echo "%=============================================================================================%"
  npm run clean:env

  if git diff --name-only --quiet ./client/src/environments/*; then
    true
  else
    git add ./client/src/environments/* && git commit --amend --no-edit --no-verify
  fi
fi
