#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

x=1
if git diff --cached --quiet -- "api/*.ts"; then
  echo "%===================================%"
  echo "= $x No changes in API (Skipping)"
  echo "%===================================%"
else 
  echo "%===================================%"
  echo "= $x Found changes in API."
  echo "%===================================%"
  {
    echo "%===================================%"
    echo "= $x:A Linting API..."
    echo "%===================================%"
    npm run lint:api
  } || {
    x=x+0.5
    echo "%===================================%"
    echo "= X You have eslint errors in API. Please fix them before committing." 1>&2
    echo "%===================================%"
    false
  }

  echo "%===================================%"
  echo "= $x:B Formatting API..."
  echo "%===================================%"
  npm run format:api

  x=$((x+1))
fi


if git diff --cached --quiet -- "client/*.ts"; then
  echo "%===================================%"
  echo "= $x No changes in Client (Skipping)"
  echo "%===================================%"
else
  echo "%===================================%"
  echo "= $x Found changes in Client."
  echo "%===================================%"
  {
    echo "%===================================%"
    echo "= $x:A Linting Client..."
    echo "%===================================%"
    npm run lint:client
  } || {
    echo "%===================================%"
    echo "= X You have eslint errors in Client. Please fix them before committing." 1>&2
    echo "%===================================%"
    false
  }

  echo "%===================================%"
  echo "= $x:B Formatting Client..."
  echo "%===================================%"
  npm run format:client

  echo "%===================================%"
  echo "= $x:C Removing environment variables..."
  echo "%===================================%"
  npm run clean:env
  git add . && git commit --amend --no-edit
fi
